import numpy as np
arr=np.arange(12).reshape(2,2,3)
print(arr)
print("--------------------------------")
arr=arr.transpose(0,2,1)
print(arr)
print("--------------------------------")
arr=np.arange(12).reshape(2,2,3).transpose(0,2,1)
print(arr)
print("--------- -----------  4차원  ----------------------")
arr=np.arange(24).reshape(2,2,2,3)
print(arr)
print("--------------------------------")
arr=arr.transpose(0,3,1,2)
print(arr)
